name: Generate sitemap
on:
  push:
    branches:
      - main
    paths:
      - '**/*.html'
jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo with full history # Added descriptive name
        uses: actions/checkout@v4
        with:
          # THIS IS THE CRITICAL LINE TO FIX THE LASTMOD DATE ISSUE
          fetch-depth: 0 
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://sidhiandassociates.github.io/
          sitemap-format: xml
      - name: Remove .html extensions from sitemap
        run: sed -i 's/\.html//g' sitemap.xml
      - name: Commit sitemap if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push
